version: '3'

services:
  whisper-api:
    image: closiqode/server-whisper:latest
    container_name: whisper-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
      - ./models:/app/models
    environment:
      - JWT_SECRET_KEY=49f85d9ae0eadab02f28f1c0d4118ac0effca0197e27c116f9a4f580c0d91c7e
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=changez_ce_mot_de_passe
      - MODEL_SIZE=tiny
      - DEVICE=cpu
      - COMPUTE_TYPE=int8
    command: python server_faster_whisper.py
    labels:
      - "com.github.repo=https://github.com/ClosiQode/server-whisper"
      - "com.casaos.name=Whisper API"
      - "com.casaos.description=API sécurisée pour la transcription audio avec Faster Whisper"
      - "com.casaos.developer=ClosiQode"
      - "com.casaos.icon=https://raw.githubusercontent.com/ClosiQode/server-whisper/main/assets/icon.svg"
